SpinnySideUp/Models/Flight.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SpinnySideUp.Models
{
    public class Flight
    {
        [Key] //primary key
        public int FlightId { get; set; }
        public DateTime Date { get; set; }
        public string Duty { get; set; }
        public string Seat { get; set; }
        public string Mission { get; set; }
        public decimal Day { get; set; }
        public decimal Night { get; set; }
        public decimal NightGoggles { get; set; }
        public decimal NightSystems { get; set; }
        public decimal Weather { get; set; }
        public string AircraftId { get; set; }
        public string Notes { get; set; }

        [ForeignKey("User")]
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
    public class FlightDto
    {
        public int FlightId { get; set; }

        [DisplayName("Flight Date")]
        [Required(ErrorMessage = "Please Enter a Date DD/MM/YYYY")]
        public DateTime Date { get; set; }
        [DisplayName("Duty")]
        public string Duty { get; set; }
        [DisplayName("Seat")]
        public string Seat { get; set; }
        [DisplayName("Mission Type")]
        public string Mission { get; set; }
        [DisplayName("Day Hours")]
        public decimal Day { get; set; }
        [DisplayName("Night Hours")]
        public decimal Night { get; set; }
        [DisplayName("NightGoggle Hours")]
        public decimal NightGoggles { get; set; }
        [DisplayName("NightSystem Hours")]
        public decimal NightSystems { get; set; }
        [DisplayName("Weather Hours")]
        public decimal Weather { get; set; }
        [DisplayName("Aircraft Number")]
        public string AircraftId { get; set; }
        [DisplayName("Notes")]
        public string Notes { get; set; }
        public string UserId { get; set; }
    }
}

SpinnySideUp/Controllers/FlightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using SpinnySideUp.Models.ViewModels;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Diagnostics;
using System.Web.Script.Serialization;
using SpinnySideUp.Models;
using System.Net;
using Microsoft.AspNet.Identity;

namespace SpinnySideUp.Controllers
{
    public class FlightController : Controller
    {
        private JavaScriptSerializer jss = new JavaScriptSerializer();
        private static readonly HttpClient client;
        static FlightController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };
            client = new HttpClient(handler);
            //My Port # is 44314
            client.BaseAddress = new Uri("https://localhost:44314/api/");
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            //warning function ignoring:
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
        }
        // GET: Flight
        //Flight/List
        // LIST ALL THE FLIGHTS IN VIEW:
        public ActionResult List()
        {
            string url = "FlightData/GetFlights";// from data controller GetFlights

            HttpResponseMessage response = client.GetAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<FlightDto> SelectedFlight = response.Content.ReadAsAsync<IEnumerable<FlightDto>>().Result;
                return View(SelectedFlight);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //GET Flight/Details/3
        public ActionResult Details(int id)
        {
            ShowFlight ViewModels = new ShowFlight();
            string FlightDetailurl = "Flightdata/findFlight/" + id;
            HttpResponseMessage findFlightresponse = client.GetAsync(FlightDetailurl).Result;

            if (findFlightresponse.IsSuccessStatusCode)
            {

                FlightDto SelectedFlight = findFlightresponse.Content.ReadAsAsync<FlightDto>().Result;
                ViewModels.Flight = SelectedFlight;

                return View(ViewModels);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        public ActionResult Index()
        {
            return View();
        }

        //ADD/CREATE new Flight
        // GET:Flight/Create 
        [HttpGet]
        public ActionResult Create()//FORM Imputs from view
        {
            return View();
        }

        //POST Flight/Create
        //Posts to DB and creats new Flight if form entries are correct
        //send request to Data controller. 

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Create(Flight FlightInfo)
        {
            string AddFlightUrl = "FlightData/AddFlight"; //AddFlight model created in data controller
            FlightInfo.UserId = User.Identity.GetUserId();//USER ID WHO CREATES FLIGHT

            HttpContent content = new StringContent(jss.Serialize(FlightInfo));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage AddFlightResponse = client.PostAsync(AddFlightUrl, content).Result;

            if (AddFlightResponse.IsSuccessStatusCode)
            {

                int FlightId = AddFlightResponse.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Details", new { id = FlightId });
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

        //UPDATE FLIGHTS
        //EDIT Flight callls on update 
        //GET: Flight/Edit/5
        public ActionResult Edit(int id)
        {

            UpdateFlight ViewModels = new UpdateFlight();

            string GetUpdateFlightUrl = "FlightData/findFlight/" + id;//locate Flight by id
            HttpResponseMessage FindFlightResponse = client.GetAsync(GetUpdateFlightUrl).Result;

            if (FindFlightResponse.IsSuccessStatusCode)
            {
                //Put data into DepartmentDto
                FlightDto SelectedFlight = FindFlightResponse.Content.ReadAsAsync<FlightDto>().Result;
                ViewModels.Flight = SelectedFlight;

                return View(ViewModels);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //POST UPDATE
        // POST: Department/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Edit(int id, Flight FlightInfo)
        {
            string PostUpdateFlightUrl = "FlightData/UpdateFlight/" + id;
            FlightInfo.UserId = User.Identity.GetUserId();
            Debug.WriteLine(FlightInfo);
            HttpContent content = new StringContent(jss.Serialize(FlightInfo));
            Debug.WriteLine(FlightInfo);

            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage UpdateFlightResponse = client.PostAsync(PostUpdateFlightUrl, content).Result;

            if (UpdateFlightResponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Details", new { id = id });
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //DELETE FLIGHT:
        //Get Request Flight/Delete/3
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            string GetFlightDeleteUrl = "Flightdata/findFlight/" + id;//find the releventFlight
            HttpResponseMessage DeleteFlightResponse = client.GetAsync(GetFlightDeleteUrl).Result;

            if (DeleteFlightResponse.IsSuccessStatusCode)
            {
                //Put data into player data transfer object
                FlightDto SelectedFlight = DeleteFlightResponse.Content.ReadAsAsync<FlightDto>().Result;
                return View(SelectedFlight);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
        //POST REQUEST TO DELETE
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            string PostFlightDeleteUrl = "Flightdata/deleteFlight/" + id;

            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(PostFlightDeleteUrl, content).Result;

            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }


    }
}

SpinnySideUp/Views/Flight/Create.cshtml
@model SpinnySideUp.Models.FlightDto
@{
    ViewBag.Title = "Create";
}

<h2>Add a Flight:</h2>
<div class="card-header">
    <ul class="nav nav-pills card-header-pills">
        <li class="nav-item">
            @Html.ActionLink("Cancel", "List")
        </li>
    </ul>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger", data_valmsg_for = "Date" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Duty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Duty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Duty, "", new { @class = "text-danger", data_valmsg_for = "Duty" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Seat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Seat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Seat, "", new { @class = "text-danger", data_valmsg_for = "Seat" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Mission, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mission, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mission, "", new { @class = "text-danger", data_valmsg_for = "Mission" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.AircraftId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AircraftId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AircraftId, "", new { @class = "text-danger", data_valmsg_for = "AircraftId" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger", data_valmsg_for = "Notes" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger", data_valmsg_for = "Day" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Night, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Night, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Night, "", new { @class = "text-danger", data_valmsg_for = "Night" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NightGoggles, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NightGoggles, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NightGoggles, "", new { @class = "text-danger", data_valmsg_for = "NightGoggles" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NightSystems, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NightSystems, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NightSystems, "", new { @class = "text-danger", data_valmsg_for = "NightSystems" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Weather, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Weather, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Weather, "", new { @class = "text-danger", data_valmsg_for = "Weather" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

SpinnySideUp/Views/Flight/DeleteConfirm.cshtml
@model SpinnySideUp.Models.FlightDto

@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Delete Flight #  @Model.Date</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">@Model.Date</h5>
            <h6 class="card-subtitle mb-2 text-muted">@Model.Duty</h6>
            <p class="card-text">@Model.Seat</p>
            <p class="card-text">@Model.Mission</p>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "Flight", new { id = Model.FlightId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Cancel", "List")
        </div>
    }
</div>

SpinnySideUp/Views/Flight/Details.cshtml
@model SpinnySideUp.Models.ViewModels.ShowFlight
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div class="card text-left">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                @Html.ActionLink("All Flights", "List")
            </li>
            <li class="nav-item">
                @Html.ActionLink("Edit", "Edit", new { id = Model.Flight.FlightId })
            </li>
            <li class="nav-item">
                @Html.ActionLink("Delete", "DeleteConfirm", new { id = Model.Flight.FlightId })
            </li>
        </ul>
    </div>
    <div class="card-body">
        <h5 class="card-title">@Model.Flight.Date </h5>

        <p class="card-text"><h7>Duty:</h7> @Model.Flight.Duty </p>
        <p class="card-text"><h7>Seat:</h7> @Model.Flight.Seat </p>
        <p class="card-text"><h7>Mission:</h7> @Model.Flight.Mission </p>
        <p class="card-text"><h7>Aircraft ID:</h7> @Model.Flight.AircraftId </p>
       
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Day</th>
                    <th scope="col">Night</th>
                    <th scope="col">NightGoggles</th>
                    <th scope="col">NightSystems</th>
                    <th scope="col">Weather</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>@Model.Flight.Day</td>
                    <td>@Model.Flight.Night</td>
                    <td>@Model.Flight.NightGoggles</td>
                    <td>@Model.Flight.NightSystems</td>
                    <td>@Model.Flight.Weather</td>
                </tr>
            </tbody>
        </table>


        <p class="card-text"><h7>Notes:</h7> @Model.Flight.Notes </p>
        <a href="#" class="btn btn-primary">Share</a>
    </div>
</div>

SpinnySideUp/Views/Flight/Edit.cshtml
@model SpinnySideUp.Models.ViewModels.UpdateFlight
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Flight", new { id = Model.Flight.FlightId }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Flight Editing</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Flight.FlightId, new { Name = "FlightId" })

    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Date, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Date, new { htmlAttributes = new { @class = "form-control", Name = "Date" } })
            @Html.ValidationMessageFor(model => model.Flight.Date, "", new { @class = "text-danger", data_valmsg_for = "Date" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Duty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Duty, new { htmlAttributes = new { @class = "form-control", Name="Duty" } })
            @Html.ValidationMessageFor(model => model.Flight.Duty, "", new { @class = "text-danger", data_valmsg_for = "Duty" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Seat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Seat, new { htmlAttributes = new { @class = "form-control", Name="Seat"} })
            @Html.ValidationMessageFor(model => model.Flight.Seat, "", new { @class = "text-danger", data_valmsg_for = "Seat" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Mission, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Mission, new { htmlAttributes = new { @class = "form-control", Name="Mission" } })
            @Html.ValidationMessageFor(model => model.Flight.Mission, "", new { @class = "text-danger", data_valmsg_for = "Mission" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.AircraftId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.AircraftId, new { htmlAttributes = new { @class = "form-control", Name="AircraftId" } })
            @Html.ValidationMessageFor(model => model.Flight.AircraftId, "", new { @class = "text-danger", data_valmsg_for = "AircraftId" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Notes, new { htmlAttributes = new { @class = "form-control", Name="Notes" } })
            @Html.ValidationMessageFor(model => model.Flight.Notes, "", new { @class = "text-danger", data_valmsg_for = "Notes" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Day, htmlAttributes: new { @class = "control-label col-md-2", Name="Day" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Day, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Flight.Day, "", new { @class = "text-danger", data_valmsg_for = "Day" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Night, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Night, new { htmlAttributes = new { @class = "form-control", Name="Night" } })
            @Html.ValidationMessageFor(model => model.Flight.Night, "", new { @class = "text-danger", data_valmsg_for = "Night" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.NightGoggles, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.NightGoggles, new { htmlAttributes = new { @class = "form-control" , Name="NightGoggles"} })
            @Html.ValidationMessageFor(model => model.Flight.NightGoggles, "", new { @class = "text-danger", data_valmsg_for = "NightGoggles" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.NightSystems, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.NightSystems, new { htmlAttributes = new { @class = "form-control", Name="NightSystems" } })
            @Html.ValidationMessageFor(model => model.Flight.NightSystems, "", new { @class = "text-danger", data_valmsg_for = "NightSystems" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Flight.Weather, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Flight.Weather, new { htmlAttributes = new { @class = "form-control", Name="Weather" } })
            @Html.ValidationMessageFor(model => model.Flight.Weather, "", new { @class = "text-danger", data_valmsg_for = "Weather" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

SpinnySideUp/Views/Flight/List.cshtml
@model IEnumerable<SpinnySideUp.Models.FlightDto>

@{
    ViewBag.Title = "List Flights";
}
<h1>Flights</h1>
<div class="card text-left">
    <div class="card-header">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                @Html.ActionLink("Add Flight", "Create")
            </li>
        </ul>
    </div>
</div>

    <br />

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Duty</th>
                <th scope="col">Seat</th>
                <th scope="col">Mission</th>
                <th scope="col">AircraftId</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var Flightitem in Model)
            {

                <tr>
                    <th scope="col">@Flightitem.Date</th>
                    <th scope="col">@Flightitem.Duty</th>
                    <th scope="col">@Flightitem.Seat</th>
                    <th scope="col">@Flightitem.Mission</th>
                    <th scope="col">@Flightitem.AircraftId</th>
                    <th scope="col">
                        <div class="card-header">
                            <ul class="nav nav-pills card-header-pills">
                                <li class="nav-item">
                                    @Html.ActionLink("Details", "Details", new { id = Flightitem.FlightId })
                                </li>
                                <li class="nav-item">
                                    @Html.ActionLink("Edit", "Edit", new { id = Flightitem.FlightId })
                                </li>
                            </ul>
                        </div>
                    </th>

                </tr>


            }
        </tbody>
    </table>